spring.application.name=string-utils-client
spring.main.web-application-type=none

string-utils-client.server-url=http://localhost:8080

logging.structured.format.console=logstash
logging.structured.json.add.service.name=${spring.application.name}
logging.structured.json.add.service.version=${project.version:0.0.1-SNAPSHOT}
